### PR TITLE
Update to 3.5.1

### PR DESCRIPTION
**Pull request by johnfg2610**
I have run the tests and they all seem to be passing just fine.
image
 I've fixed the auth handler and updated relevant classes. 
I have also updated the grade distribution to the latest version(4.6) as well as sonarqube and bintray.

### CODE REVIEW

**Comment by johnfg2610** [comment]
am i correct in thinking the tests are ment to show some errors?(im new to unit tests although im fairly sure i got more work todo)

**Comment by aesteve** [comment]
Thanks a lot for your amazing work. I did not receive any notification about it that's why I missed it.

I'll take a look more in details (and run the tests locally), but you unfortunately removed the documentation folder, can you add it back ? Thanks.

**Comment by johnfg2610** [comment]
Added the files back

**Comment by aesteve** [comment]
I tested your work, and it also works with 3.5.2.

Thanks a lot for your amazing work. I'll accept your PR, so that it "counts" as a contribution, then I'll upgrade to 3.5.2.


Thanks again.

**Pull request merged**
