### PR TITLE
Fix #68, parse Boolean fields for @Params

### LINKED ISSUE #68: Parameter adapter for Boolean.class
I'm using `@Params` to decode a FormData, but "DefaultParameterAdapter" cannot parse a boolean field to set appropriate value in my bean. It always returns bad request error (400).

### PR DESCRIPTION
**Pull request by morteza**
Fix #68 (parse boolean fields in `@Params`).

### CODE REVIEW

**Comment by aesteve** [comment]
Thank you so much.

I'll just get your work, make sure everything's fine, then merge it & release a new version.

**Comment by aesteve** [comment]
God, github is completely broken... Maybe that's because you deleted your fork ? Idk... but :

```
curl -L https://github.com/aesteve/nubes/pull/71.patch
```

doesn't show anything, I can't review your pull request locally. I have to merge blindly

**Comment by aesteve** [comment]
Works fine. I'll release a new version. Thanks again for the pull request.

**Comment by morteza** [comment]
I'm really sorry, I thought it keeps everything intact. My mistake. I'll create a new fork for future requests.

**Comment by aesteve** [comment]
No please don't be sorry, it was a very good contribution, much appreciated

**Pull request merged**
